ISSUE-5: pushing tested code

diff --git a/pretreatment b/pretreatment
--- a/pretreatment
+++ b/pretreatment
@@ -36,21 +36,22 @@ randomString=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
 # function to correct gc-bias corrected read depths using Yoon et al method 
 # uses external R script 
 function runMedianGCcorrection() {
-	awk '{print $3}' $1 | paste - $2 > ${output}_GC_correction_input.txt
-	Rscript --slave ${SOURCEDIR}/source/R/gcCorrectionYoon.R ${output}_GC_correction_input.txt "gc" > ${output}_GC_correction_output.txt;
-	paste $1 ${output}_GC_correction_output.txt | awk '{print $1,$2,$5,$4}' > temp_${randomString}.txt
-    mv temp_${randomString}.txt $1
-    rm ${output}_GC_correction_input.txt ${output}_GC_correction_output.txt temp_${randomString}.txt;
+	awk '{print $1}' $1 > $1"_GC"
+	paste $1"_GC" $2 > $output"_GC"
+	Rscript --slave $SOURCEDIR"/source/R/gcCorrectionYoon.R" $output"_GC" "gc"> $1"_GC";
+	awk '{print $2,$3,$4,$5}' $1 | paste $1"_GC" - >$output"_GC"
+	mv $output"_GC" $1
+	rm $1"_GC";
 }
 
 # function calls an external script loessGCCorrection.R
 # does gc correction using loess method
 function runLoessGCcorrection() {
-	awk '{print $3}' $1 > ${output}_GC_correction.txt
-	Rscript --slave ${SOURCEDIR}/source/R/loessGCCorrection.R ${output}_GC_correction.txt $2
-	paste $1 ${output}_GC_correction.txt | awk '{print $1,$2,$5,$4}' > temp_${randomString}.txt
-	mv temp_${randomString}.txt $1
-	rm ${output}_GC_correction.txt temp_${randomString}.txt;
+	awk '{print $1}' $1 > $1"_GC"
+	Rscript --slave $SOURCEDIR"/source/R/loessGCCorrection.R" $1"_GC" $2
+	awk '{print $2,$3,$4,$5}' $1 | paste $1"_GC" - >$output"_GC"
+	mv $output"_GC" $1
+	rm $1"_GC";
 }
 
 
@@ -58,11 +59,13 @@ function runLoessGCcorrection() {
 # Similar to above function
 # Instead of GC score , mappability score is passed. 
 function runMedianMapCorrection(){
-	awk '{print $3,$4}' $1  > ${output}_map_correction_input.txt
-	Rscript --slave ${SOURCEDIR}/source/R/gcCorrectionYoon.R ${output}_map_correction_input.txt "map"> ${output}_map_correction_output.txt
-	paste $1 ${output}_map_correction_output.txt | awk '{print $1,$2,$5,$4}' > temp_${randomString}.txt
-	mv temp_${randomString}.txt $1
-	rm ${output}_map_correction_input.txt ${output}_map_correction_output.txt temp_${randomString}.txt
+	
+	awk '{print $1,$3}' $1 > $randomString"_map_rawRead.input"
+	Rscript --slave $SOURCEDIR"/source/R/gcCorrectionYoon.R" $randomString"_map_rawRead.input" "map"> $randomString"_map_rawRead.output";
+	awk '{print $2,$3,$4,$5}' $1 | paste $randomString"_map_rawRead.output" - >$randomString"_temp.txt"
+	mv $randomString"_temp.txt" $1
+	rm -rf $randomString"_map_rawRead.input" $randomString"_map_rawRead.output"
+
 }
 
 #***************************************#
@@ -70,8 +73,8 @@ function runMedianMapCorrection(){
 #	AND SET PARAMETERS		#
 #***************************************#
 
-SHORTOPTS="ybp:i:o:m:w:"
-LONGOPTS="gcfile:,mapThres:,help,medianGC,medianMap,loessGC,chromosome:,chrlen:"
+SHORTOPTS="ybp:i:o:z:"
+LONGOPTS="gcfile:,mapfile:,mapThres:,help,medianGC,medianMap,loessGC"
 PROGNAME="preprocess.sh"
 ARGS=$(getopt -s bash --options $SHORTOPTS  --longoptions $LONGOPTS --name $PROGNAME -- "$@" ) 
 
@@ -81,15 +84,13 @@ while true; do
 	-p) no_of_procs="$2"; shift 2 ;;
 	-i) input_file="$2"; shift 2;;
 	-o) output="$2"; shift 2;;
-	-w) window_size="$2"; shift 2 ;;
-	-m) mappability_file="$2"; shift 2;;
+	--mapfile) mappability_file="$2"; shift 2;;
+	-z) window_file="$2"; shift 2;;
 	-y) MEDIANGCFLAG=1; MEDIANMAPFLAG=1; shift ;;
 	--gcfile) gcFile="$2"; gcFlag=1; shift 2; ;;
 	--help) echo "Usage: preprocess -i <input BAM> -o <output Prefix> -m <mappability file> -z <bin file>";
 		exit 1; ;;
 	--mapThres) mapThres="$2" ; shift 2; ;;
-	--chromosome) chromosome="$2" ; shift 2; ;;
-	--chrlen) chromosomeLength="$2" ; shift 2; ;;
 	--medianGC) MEDIANGCFLAG=1; shift ;; 
 	--medianMap) MEDIANMAPFLAG=1; shift ;;
 	--loessGC) LOESSGCFLAG=1; shift ;;
@@ -102,21 +103,21 @@ done
 
 
 # MINIMUM REQUIRED PARAMETERS
-if [[ -z "$input_file" || -z "$mappability_file" || -z "$output" ]]; then
+if [[ -z "$input_file" || -z "$window_file" || -z "$mappability_file" || -z "$output" ]]; then
 	echo "Missing one of the required parameters: window_file (-z) mappability_file (-m) input_file (-i) output (-o) " >&2
 	exit 
 fi
 
 # FILE DOESNT EXIST ERROR
-if [[ ! -f $input_file || ! -f $mappability_file ]]; then
+if [[ ! -f $window_file || ! -f $input_file || ! -f $mappability_file ]]; then 
 	echo "One of the input files not found" >&2
 	exit 1
 fi
-if [[ $MEDIANGCFLAG -eq 1  || $LOESSGCFLAG -eq 1 ]]; then
+if [[ $MEDIANGCFLAG -eq 1 ]]; then 
 	if [[ $gcFlag -eq 1 ]];then
 		gcFlag=1;
 	else
-		echo "ERROR: gcflag requires --gcfile argument" >&2 ;
+		echo "ERROR: -y flag requires --gcfile argument" >&2 ;
 		exit 1
 	fi
 fi	
@@ -127,27 +128,31 @@ fi
 #***********************************************#
 
 # DATA PREPARATION AND FILTERING 
-Rscript --slave ${SOURCEDIR}/source/R/CalculateCoverage.R ${input_file} ${output} ${window_size} ${chromosome} ${chromosomeLength}
-paste ${output}_preproc_intermediate.txt $mappability_file  > temp.txt
-mv temp.txt ${output}_preproc_intermediate.txt
+
+Rscript --slave $SOURCEDIR"/source/R/binCoverage.R" $input_file $window_file > RD 
+paste $window_file RD $mappability_file > $output"_temp1.bed"
+awk '{print $4,$4,$5,$2,$3}' $output"_temp1.bed"> $output"_temp1";
 
 # check for gc correction, if yes correct 
 # check whether to correct with Yoon method or Loess Method
 if [[ $MEDIANGCFLAG -eq 1 ]]; then
-	runMedianGCcorrection ${output}_preproc_intermediate.txt $gcFile ;
+	runMedianGCcorrection $output"_temp1" $gcFile ;
 elif [[ $LOESSGCFLAG -eq 1 ]]; then
-	runLoessGCcorrection ${output}_preproc_intermediate.txt $gcFile
+	runLoessGCcorrection $output"_temp1" $gcFile
 fi
 
 # check for mappability correction, if yes correct it 
 if [[ $MEDIANMAPFLAG -eq 1 ]]; then
-	runMedianMapCorrection ${output}_preproc_intermediate.txt
+	runMedianMapCorrection $output"_temp1"
 fi
 
 
-awk -v mapThres="$mapThres" '{if($3!=0 && $4>=mapThres) print $3;}' ${output}_preproc_intermediate.txt > ${output}_pCNVD.input;
-awk -v mapThres="$mapThres" '{if($3!=0 && $4>=mapThres) print $1,$2;}' ${output}_preproc_intermediate.txt > ${output}_pCNVD.bincor;
+awk -v mapThres="$mapThres" '{if($1!=0&&$2!=0&&$3>=mapThres) print $1;}' $output"_temp1" > $output"_pCNVD.input";
+awk -v mapThres="$mapThres" '{if($1!=0&&$2!=0&&$3>=mapThres)print $4,$5;}' $output"_temp1" > $output"_pCNVD.bincor"; 
+rm -rf $output"_temp1.bed" $output"_temp1" RD;
 
-rm ${output}_preproc_intermediate.txt
+
+# check for gc correction flag and run external R script 
+##############################################################################################
 
 
